<#
    .NOTES
    Generated by SwitchCraft
    .DESCRIPTION
    Template Powershell Script for Intune Package Installations
    .OUTPUTS
    C:\ProgramData\Microsoft\IntuneManagementExtension\Logs\
    .EXAMPLE
    Installation:   "%systemroot%\sysnative\WindowsPowerShell\v1.0\powershell.exe" -noprofile -executionpolicy bypass -file .\install.ps1 -InstallMode Install -AdminPermissions
    Uninstallation: "%systemroot%\sysnative\WindowsPowerShell\v1.0\powershell.exe" -noprofile -executionpolicy bypass -file .\install.ps1 -InstallMode Uninstall -AdminPermissions
#>

param(
    [Parameter(Mandatory = $True)] [ValidateSet("Install", "Uninstall", "install", "uninstall")] [Alias('install')] [String] $InstallMode,
    [Parameter(Mandatory = $False)] [Alias('Path')] [String] $logpath = "$env:ProgramData\Microsoft\IntuneManagementExtension\Logs\",
    [Parameter(Mandatory = $False)] [Switch] $AdminPermissions = $false
)
$ExitCode = 0

# Log Setup
If (!(test-path $logpath)) { New-Item -ItemType Directory -Force -Path $logpath >$null 2>&1 }
$logpath = $logpath + "SwitchCraft-App-" + $MyInvocation.MyCommand.Name + ".log"

function Write-ToLog {
    param ([string]$Warning, [string]$LogText)
    $TimeStr = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Add-Content $logpath "$TimeStr || $LogText" -ErrorAction SilentlyContinue
}

Write-ToLog -Warning 9 -LogText "Starting Log File of App Installation $($MyInvocation.MyCommand.Name)"
Write-ToLog -Warning 1 -LogText "Work Directory: $(Get-Location)"

# Check Admin
if (($AdminPermissions -eq $true)) {
    $currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
    if (-not ($currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator))) {
        Write-ToLog -Warning 3 -LogText "Admin permissions required but not present."
        Exit 2
    }
}

function Start-Process-Function {
    param($FilePath, $ArgumentList)
    Write-ToLog -Warning 1 -LogText "Starting $FilePath with args: $ArgumentList"
    try {
        $proc = Start-Process -filePath $FilePath -ArgumentList $ArgumentList -PassThru -WindowStyle hidden -Wait
        return $proc.ExitCode
    } catch {
        Write-ToLog -Warning 3 -LogText "Error executing: $_"
        return 1
    }
}

# ## INSTALLATION
if (($InstallMode -eq "Install") -or ($InstallMode -eq "i")) {
    $Installer = Join-Path -Path $PSScriptRoot -ChildPath "{{INSTALLER_FILE}}"
    $ExitCode = Start-Process-Function -FilePath $Installer -ArgumentList "{{INSTALL_ARGS}}"
}

# ## UNINSTALLATION
if (($InstallMode -eq "Uninstall") -or ($InstallMode -eq "u")) {
    # Uninstall Logic
    $UninstallKey = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall"
    $UninstallKey32 = "HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall"

    # Try to find by name
    $app = Get-ChildItem $UninstallKey, $UninstallKey32 -ErrorAction SilentlyContinue | Get-ItemProperty | Where-Object { $_.DisplayName -like "*{{APP_NAME}}*" } | Select-Object -First 1

    if ($app) {
        Write-ToLog -Warning 1 -LogText "Found app: $($app.DisplayName)"
        if ($app.UninstallString -match "MsiExec.exe") {
             $guid = $app.PSChildName
             Start-Process-Function -FilePath "msiexec.exe" -ArgumentList "/x $guid /qn"
        } else {
             # Silent uninstall string might need verification
             # Start-Process-Function -FilePath $app.UninstallString -ArgumentList "/S"
             Write-ToLog -Warning 2 -LogText "Non-MSI uninstall detected, verify arguments: $($app.UninstallString)"
        }
    } else {
        Write-ToLog -Warning 1 -LogText "App {{APP_NAME}} not found for uninstall."
    }
}

Write-ToLog -Warning 1 -LogText "Script finished with Exitcode $ExitCode"
Exit $ExitCode
