<#
    .NOTES
    Generated by SwitchCraft v{{SWITCHCRAFT_VERSION}}
    GitHub: {{SWITCHCRAFT_GITHUB}}

    .DESCRIPTION
    Template Powershell Script for Intune Package Installations.
    Features: CMTrace Logging, Error Handling, Process Execution Wrapper.

    .OUTPUTS
    C:\ProgramData\Microsoft\IntuneManagementExtension\Logs\
#>

param(
    [Parameter(Mandatory = $True)] [ValidateSet("Install", "Uninstall", "install", "uninstall")] [Alias('install')] [String] $InstallMode,
    [Parameter(Mandatory = $False)] [Alias('Path')] [String] $logpath = "$env:ProgramData\Microsoft\IntuneManagementExtension\Logs\",
    [Parameter(Mandatory = $False)] [Switch] $AdminPermissions = $false
)

$ErrorActionPreference = "Stop"
$ExitCode = 0
$AppName = "{{APP_NAME}}"
$ScriptVersion = "{{SWITCHCRAFT_VERSION}}"

# --- Logging Setup (CMTrace Compatible) ---
if (!(Test-Path $logpath)) {
    try { New-Item -ItemType Directory -Force -Path $logpath -ErrorAction SilentlyContinue | Out-Null } catch {}
}
$LogFile = Join-Path $logpath ("SwitchCraft-App-" + $AppName + ".log")

function Write-Log {
    param(
        [ValidateSet("Info", "Warning", "Error")] [string]$Type = "Info",
        [Parameter(Mandatory=$true)] [string]$Message
    )
    $Time = Get-Date -Format "HH:mm:ss.fff"
    $Date = Get-Date -Format "MM-dd-yyyy"

    # CMTrace format: <![LOG[Message]LOG]!><time="HH:mm:ss.fff+000" date="MM-dd-yyyy" component="Script" context="" type="1" thread="" file="">
    $Severity = switch ($Type) { "Info" {1} "Warning" {2} "Error" {3} Default {1} }
    $LogEntry = "<![LOG[$Message]LOG]!><time=""$Time+000"" date=""$Date"" component=""$AppName"" context=""$env:USERNAME"" type=""$Severity"" thread=""$PID"" file=""install.ps1"">"

    try {
        Add-Content -Path $LogFile -Value $LogEntry -ErrorAction SilentlyContinue
    } catch {
        Write-Host "[$Type] $Message"
    }
}

function Show-Notification {
    param([string]$Title, [string]$Message)
    if ([System.Environment]::UserName.ToUpper() -ne "SYSTEM") {
        try {
            [void] [System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")
            $objIcon = [System.Windows.Forms.NotifyIcon]::new()
            $objIcon.Icon = [System.Drawing.Icon]::ExtractAssociatedIcon($PSHOME + "\powershell.exe")
            $objIcon.Visible = $true
            $objIcon.ShowBalloonTip(3000, $Title, $Message, [System.Windows.Forms.ToolTipIcon]::Info)
            $objIcon.Dispose()
        } catch {
            Write-Log -Type Warning "Toast Notification failed: $_"
        }
    }
}

Write-Log -Type Info "--- Starting Script Execution v$ScriptVersion ---"
Write-Log -Type Info "Action: $InstallMode | User: $env:USERNAME"

# --- Pre-Checks ---
if ($AdminPermissions) {
    if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        Write-Log -Type Error "Admin permissions required but not detected."
        exit 1603
    }
}

function Start-Process-Function {
    param($FilePath, $ArgumentList)
    Write-Log -Type Info "Exec: $FilePath $ArgumentList"
    try {
        $proc = Start-Process -FilePath $FilePath -ArgumentList $ArgumentList -PassThru -WindowStyle Hidden -Wait
        $code = $proc.ExitCode
        Write-Log -Type Info "ExitCode: $code"
        return $code
    } catch {
        Write-Log -Type Error "Exec Failed: $_"
        return 1603
    }
}

try {
    # --- INSTALL ---
    if ($InstallMode -match "^(Install|i)$") {
        $InstallerFile = "{{INSTALLER_FILE}}"
        $InstallerPath = Join-Path -Path $PSScriptRoot -ChildPath $InstallerFile

        if (!(Test-Path $InstallerPath)) { throw "Installer missing: $InstallerPath" }

        # Version Check
        if ($InstallerFile -match "\.(exe|dll)$") {
            try { $ver = (Get-Item $InstallerPath).VersionInfo.ProductVersion; Write-Log -Type Info "Version: $ver" } catch {}
        }

        $ExitCode = Start-Process-Function -FilePath $InstallerPath -ArgumentList "{{INSTALL_ARGS}}"

        if ($ExitCode -eq 0 -or $ExitCode -eq 3010) {
            Show-Notification -Title "Success" -Message "$AppName installed."
        } else {
             Show-Notification -Title "Error" -Message "$AppName failed ($ExitCode)."
        }
    }

    # --- UNINSTALL ---
    if ($InstallMode -match "^(Uninstall|u)$") {
        $SearchName = "*{{APP_NAME}}*"
        Write-Log -Type Info "Uninstall Search: $SearchName"

        $paths = @("HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall", "HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall")
        $app = Get-ChildItem -Path $paths -ErrorAction SilentlyContinue | Get-ItemProperty | Where-Object { $_.DisplayName -like $SearchName } | Select-Object -First 1

        if ($app) {
            Write-Log -Type Info "Found: $($app.DisplayName)"
            $cmd = $app.UninstallString
            $params = "/S"

            if ($app.UninstallString -match "MsiExec.exe") {
                 $cmd = "msiexec.exe"
                 $params = "/x $($app.PSChildName) /qn"
                 $ExitCode = Start-Process-Function -FilePath $cmd -ArgumentList $params
            } else {
                 if ($cmd -match '^"(.+?)"$') { $cmd = $matches[1] }
                 if ($cmd -match "\.exe\s+") {
                     Write-Log -Type Warning "Complex UninstallString: $cmd"
                     $ExitCode = (Start-Process -FilePath "cmd.exe" -ArgumentList "/c $cmd" -PassThru -WindowStyle Hidden -Wait).ExitCode
                 } else {
                     $ExitCode = Start-Process-Function -FilePath $cmd -ArgumentList "/S"
                 }
            }
        } else {
            Write-Log -Type Warning "App not found for uninstall."
        }
    }

} catch {
    Write-Log -Type Error "CRITICAL: $_"
    $ExitCode = 1
}

Write-Log -Type Info "End. ExitCode: $ExitCode"
Exit $ExitCode
