backend:
  - changed-files:
    - any-glob-to-any-file: 'src/**/*'
    - any-glob-to-any-file: 'tests/**/*'
    - any-glob-to-any-file: 'pyproject.toml'
    - any-glob-to-any-file: 'setup.py'
    - any-glob-to-any-file: 'requirements.txt'

frontend:
  - changed-files:
    - any-glob-to-any-file: 'frontend/**/*'

ci-cd:
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'

documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
    - any-glob-to-any-file: 'docs/**/*'
    - any-glob-to-any-file: 'LICENSE'
