import flet as ft
from switchcraft.services.intune_service import IntuneService
from switchcraft.utils.config import SwitchCraftConfig
import logging

logger = logging.getLogger(__name__)

class MacOSWizardView(ft.Column):
    def __init__(self, page: ft.Page):
        super().__init__(expand=True)
        self.app_page = page
        self.intune_service = IntuneService()

        # State
        self.dmg_url = ""
        self.generated_script = ""

        self._init_ui()

    def _init_ui(self):
        self.controls = [
            ft.Text("MacOS Package Wizard", size=28, weight=ft.FontWeight.BOLD),
            ft.Text("Deploy DMG/PKG files via Intune Shell Scripts", size=16, color=ft.Colors.GREY),
            ft.Divider(),
            self._build_content()
        ]

    def _build_content(self):
        # 1. Input URL
        self.url_field = ft.TextField(
            label="Download URL (DMG or PKG)",
            hint_text="https://example.com/installer.dmg",
            expand=True
        )

        # 2. App Details
        self.app_name = ft.TextField(label="App Name (Analysis not available for URL)", width=300)
        self.bundle_id = ft.TextField(label="Bundle ID (e.g. com.example.app)", width=300)

        # 3. Validation & Generation
        self.gen_btn = ft.ElevatedButton(
            "Generate Installer Script",
            icon=ft.Icons.BUILD,
            on_click=self._generate_script
        )

        self.preview_field = ft.TextField(
            label="Generated Shell Script",
            multiline=True,
            min_lines=10,
            max_lines=15,
            text_size=12,
            font_family="Consolas",
            read_only=False
        )

        self.upload_btn = ft.ElevatedButton(
            "Upload to Intune",
            icon=ft.Icons.CLOUD_UPLOAD,
            bgcolor=ft.Colors.GREEN,
            color=ft.Colors.WHITE,
            disabled=True,
            on_click=self._upload_to_intune
        )
        self.status_txt = ft.Text("")

        return ft.Container(
            content=ft.Column([
                ft.Text("Step 1: Source Info", weight=ft.FontWeight.BOLD),
                self.url_field,
                ft.Row([self.app_name, self.bundle_id]),
                ft.Container(height=10),
                self.gen_btn,
                ft.Divider(),
                ft.Text("Step 2: Review Script", weight=ft.FontWeight.BOLD),
                self.preview_field,
                ft.Container(height=10),
                self.upload_btn,
                self.status_txt
            ], spacing=20, scroll=ft.ScrollMode.AUTO),
            padding=20
        )

    def _generate_script(self, e):
        url = self.url_field.value
        name = self.app_name.value
        # Basic validation
        if not url or not name:
             self._show_snack("URL and App Name are required", ft.Colors.RED)
             return

        # Template for DMG/PKG installation
        # Simple Logic: Download -> Mount/Install -> Cleanup
        script = f"""#!/bin/bash
# Auto-generated by SwitchCraft for {name}
# Installs from: {url}

APP_NAME="{name}"
DOWNLOAD_URL="{url}"
TEMP_DIR=$(mktemp -d)
FILENAME=$(basename "$DOWNLOAD_URL")
FILEPATH="$TEMP_DIR/$FILENAME"

echo "Downloading $APP_NAME..."
curl -L -o "$FILEPATH" "$DOWNLOAD_URL"

# Check extension
EXT="${{FILENAME##*.}}"

if [[ "$EXT" == "dmg" ]]; then
    echo "Mounting DMG..."
    MOUNTPOINT=$(hdiutil attach "$FILEPATH" -nobrowse -readonly | tail -n 1 | awk '{{print $NF}}' | tr -d '\\n')

    echo "Copying .app to /Applications..."
    # Find .app in mountpoint
    APP_PATH=$(find "$MOUNTPOINT" -maxdepth 1 -name "*.app" -print -quit)

    if [[ -n "$APP_PATH" ]]; then
        cp -R "$APP_PATH" /Applications/
        echo "Installed to /Applications/$(basename "$APP_PATH")"
    else
        echo "Error: No .app found in DMG"
        exit 1
    fi

    echo "Unmounting..."
    hdiutil detach "$MOUNTPOINT"
elif [[ "$EXT" == "pkg" ]]; then
    echo "Installing PKG..."
    installer -pkg "$FILEPATH" -target /
else
    echo "Unknown format: $EXT"
    exit 1
fi

echo "Cleaning up..."
rm -rf "$TEMP_DIR"

echo "Done."
exit 0
"""
        self.generated_script = script
        self.preview_field.value = script
        self.upload_btn.disabled = False
        self.update()

    def _upload_to_intune(self, e):
        # Authenticate
        tenant = SwitchCraftConfig.get_value("IntuneTenantID")
        client = SwitchCraftConfig.get_value("IntuneClientID")
        secret = SwitchCraftConfig.get_secure_value("IntuneClientSecret")

        if not all([tenant, client, secret]):
             self._show_snack("Intune Credentials missing in Settings", ft.Colors.RED)
             return

        self.status_txt.value = "Uploading..."
        self.upload_btn.disabled = True
        self.update()

        def _bg():
            try:
                token = self.intune_service.authenticate(tenant, client, secret)
                self.intune_service.upload_macos_shell_script(
                    token,
                    f"Install {self.app_name.value}",
                    f"Auto-generated installer for {self.app_name.value}",
                    self.preview_field.value
                )
                self.status_txt.value = "Success! Script Uploaded to MacOS > Shell Scripts."
                self.status_txt.color = ft.Colors.GREEN
            except Exception as ex:
                self.status_txt.value = f"Error: {ex}"
                self.status_txt.color = ft.Colors.RED
            finally:
                self.upload_btn.disabled = False
                self.update()

        import threading
        threading.Thread(target=_bg, daemon=True).start()

    def _show_snack(self, msg, color=ft.Colors.GREEN):
        try:
             self.app_page.snack_bar = ft.SnackBar(ft.Text(msg), bgcolor=color)
             self.app_page.snack_bar.open = True
             self.app_page.update()
        except:
            pass
