import os
import sys
import json
import re
from datetime import datetime
from pathlib import Path

def parse_issue_body(body):
    """
    Parses the GitHub Issue Form body (Markdown) into a dictionary.
    Assumes standard "### Header\n\nValue" format generated by forms.
    """
    data = {}

    # Regex to capture "### Label\n\nValue" (Value can be empty)
    # Matches: ### <Label>\n\n<Value> ... until next ### or end
    pattern = re.compile(r"###\s+(.+?)\s*\n\s*(.*?)(?=\n###|\Z)", re.DOTALL)

    matches = pattern.findall(body)

    key_map = {
        "Application Name": "app_name",
        "Product Name (Internal)": "product_name",
        "Version": "version",
        "Installer Type": "installer_type",
        "Setup Filename": "setup_file",
        "Silent Switch": "silent_switch",
        "Additional Notes": "notes"
    }

    for label, value in matches:
        label = label.strip()
        value = value.strip()

        if value == "_No response_":
            value = ""

        if label in key_map:
            data[key_map[label]] = value

    return data

def update_db(new_entry):
    db_path = Path("src/switchcraft/data/community/switches.json")

    if not db_path.exists():
        print(f"Database not found at {db_path}")
        sys.exit(1)

    try:
        with open(db_path, "r", encoding="utf-8") as f:
            db = json.load(f)
    except json.JSONDecodeError:
        print("Database JSON is corrupt.")
        sys.exit(1)

    # Validation
    required = ["app_name", "version", "silent_switch"]
    for field in required:
        if field not in new_entry or not new_entry[field]:
            print(f"Missing required field: {field}")
            sys.exit(1)

    # Add metadata
    new_entry["added_at"] = "pending-merge"
    new_entry["contributor"] = new_entry.get("contributor", "SwitchCraftBot")

    # Check for duplicate (naive check)
    for entry in db:
        if (entry.get("app_name") == new_entry.get("app_name") and
            entry.get("version") == new_entry.get("version")):
            print("Entry already exists for this version.")
            sys.exit(78)  # POSIX: configuration error - signals workflow to skip PR creation

    db.append(new_entry)

    with open(db_path, "w", encoding="utf-8") as f:
        json.dump(db, f, indent=2)

    print(f"Successfully added {new_entry['app_name']}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python process_issue_ops.py <path_to_issue_body.txt>")
        sys.exit(1)

    body_file = sys.argv[1]
    with open(body_file, "r", encoding="utf-8") as f:
        content = f.read()

    data = parse_issue_body(content)
    if not data:
        print("No structured data found in issue body.")
        sys.exit(1)

    update_db(data)
